name: Docker image build and publish
on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: Target environment
        default: "development"
        options:
          - production
          - development
      path_to_dockerfile:
        description: Path to the dockerfile
        default: "Dockerfile"
        type: string
      docker_build_dir:
        description: Docker build directory
        default: "."
        type: string
      image_tag:
        description: Tag to apply to images.
        type: string
        default: latest
      aws_region:
        description: Target AWS Region
        default: "ap-southeast-2"
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      ECR_REPO_NAME: "agroworld/aw-collection-center-ui"

    # Add explicit permissions
    permissions:
      id-token: write
      contents: read
      packages: write

    outputs:
      image: ${{ steps.build-and-push.outputs.image }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-rmodi
          aws-region: ${{ inputs.aws_region || 'ap-southeast-2' }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registries: |
            ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build and push image
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          TARGET_ENV: ${{ inputs.target_env }}
        run: |
          docker build "${{ inputs.docker_build_dir || '.' }}" \
            -f "${{ inputs.path_to_dockerfile || 'Dockerfile' }}" \
            --build-arg ENVIRONMENT=$TARGET_ENV \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
