name: Docker image build and publish
on:
  create:
    tags:
      - 'v*'  # This will trigger on version tags
  push:
    tags:
      - 'v*'  # This will trigger on version tags
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: Target environment
        default: "development"
        options:
          - production
          - development
      path_to_dockerfile:
        description: Path to the dockerfile
        default: "Dockerfile"
        type: string
      docker_build_dir:
        description: Docker build directory
        default: "."
        type: string
      image_tag:
        description: Tag to apply to images.
        type: string
        default: latest
      aws_region:
        description: Target AWS Region
        default: "ap-southeast-2"
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      ECR_REPO_NAME: "agroworld/aw-collection-center-ui"

    permissions:
      id-token: write
      contents: read
      packages: write

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE || 'github-actions-rmodi' }}
          aws-region: ${{ inputs.aws_region || 'ap-southeast-2' }}

      - name: Set default env variables
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=${{ inputs.target_env || 'development' }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ inputs.image_tag || 'latest' }}" >> $GITHUB_ENV
          fi

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registries: |
            ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          TARGET_ENV: ${{ env.DEPLOY_ENV }}
        run: |
          docker build "${{ inputs.docker_build_dir || '.' }}" -f "${{ inputs.path_to_dockerfile || 'Dockerfile' }}" --build-arg ENVIRONMENT=$TARGET_ENV -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$TARGET_ENV"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$TARGET_ENV"
          echo "IMAGE $IMAGE_TAG-$TARGET_ENV is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG-$TARGET_ENV" >> $GITHUB_OUTPUT
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-$TARGET_ENV" >> $GITHUB_OUTPUT
